/**
 * stl_writer.c — STL Binary Writer
 * 
 * Funciones para generar archivos STL binarios para impresión 3D.
 * Formato STL: 80 bytes header + 4 bytes triangle count + 50 bytes/triángulo
 * 
 * Cada triángulo: normal(3×float32) + v1(3×float32) + v2(3×float32) + v3(3×float32) + attr(uint16=0)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* Write 32-bit float in little-endian */
static void write_float32(FILE* f, float val) {
    uint32_t* p = (uint32_t*)&val;
    uint32_t le = __builtin_bswap32(*p);
    fwrite(&le, 4, 1, f);
}

/* Write 16-bit uint in little-endian */
static void write_uint16(FILE* f, uint16_t val) {
    uint16_t le = __builtin_bswap16(val);
    fwrite(&le, 2, 1, f);
}

/* Write 32-bit uint in little-endian */
static void write_uint32(FILE* f, uint32_t val) {
    uint32_t le = __builtin_bswap32(val);
    fwrite(&le, 4, 1, f);
}

/* Compute normal from three vertices (right-hand rule) */
static void compute_normal(float v1[3], float v2[3], float v3[3], float normal[3]) {
    float u[3] = {v2[0] - v1[0], v2[1] - v1[1], v2[2] - v1[2]};
    float v[3] = {v3[0] - v1[0], v3[1] - v1[1], v3[2] - v1[2]};
    
    normal[0] = u[1]*v[2] - u[2]*v[1];
    normal[1] = u[2]*v[0] - u[0]*v[2];
    normal[2] = u[0]*v[1] - u[1]*v[0];
    
    float len = sqrtf(normal[0]*normal[0] + normal[1]*normal[1] + normal[2]*normal[2]);
    if (len > 0) {
        normal[0] /= len;
        normal[1] /= len;
        normal[2] /= len;
    }
}

/* Write STL header (80 bytes) */
void stl_write_header(FILE* f, const char* description) {
    char header[80] = {0};
    if (description) {
        strncpy(header, description, 79);
    } else {
        strcpy(header, "Generated by Tritos Ternary Render Engine");
    }
    fwrite(header, 1, 80, f);
}

/* Write triangle count placeholder (4 bytes) - returns position for later update */
long stl_write_count_placeholder(FILE* f) {
    long pos = ftell(f);
    write_uint32(f, 0);
    return pos;
}

/* Update triangle count at saved position */
void stl_update_count(FILE* f, long pos, uint32_t count) {
    long current = ftell(f);
    fseek(f, pos, SEEK_SET);
    write_uint32(f, count);
    fseek(f, current, SEEK_SET);
}

/* Write a single triangle */
void stl_write_triangle(FILE* f, float v1[3], float v2[3], float v3[3]) {
    float normal[3];
    compute_normal(v1, v2, v3, normal);
    
    write_float32(f, normal[0]);
    write_float32(f, normal[1]);
    write_float32(f, normal[2]);
    
    write_float32(f, v1[0]);
    write_float32(f, v1[1]);
    write_float32(f, v1[2]);
    
    write_float32(f, v2[0]);
    write_float32(f, v2[1]);
    write_float32(f, v2[2]);
    
    write_float32(f, v3[0]);
    write_float32(f, v3[1]);
    write_float32(f, v3[2]);
    
    write_uint16(f, 0);  /* attribute bytes */
}

/* Write cube (6 faces = 12 triangles) */
void stl_write_cube(FILE* f, float x, float y, float z, float size) {
    float s = size;
    float h = s * 0.5f;
    
    /* 8 vertices of cube centered at origin */
    float v[8][3] = {
        {-h, -h, -h}, {h, -h, -h}, {h, h, -h}, {-h, h, -h},
        {-h, -h, h},  {h, -h, h},  {h, h, h},  {-h, h, h}
    };
    
    /* Translate all vertices */
    for (int i = 0; i < 8; i++) {
        v[i][0] += x;
        v[i][1] += y;
        v[i][2] += z;
    }
    
    /* 6 faces, each as 2 triangles (CCW from outside) */
    int faces[12][3] = {
        {0, 1, 2}, {0, 2, 3},  /* bottom (-Z) */
        {4, 5, 6}, {4, 6, 7},  /* top (+Z) */
        {0, 1, 5}, {0, 5, 4},  /* front (-Y) */
        {2, 3, 7}, {2, 7, 6},  /* back (+Y) */
        {1, 2, 6}, {1, 6, 5},  /* right (+X) */
        {0, 3, 7}, {0, 7, 4}   /* left (-X) */
    };
    
    for (int i = 0; i < 12; i++) {
        stl_write_triangle(f, v[faces[i][0]], v[faces[i][1]], v[faces[i][2]]);
    }
}

/* Write UV sphere (latitude/longitude bands) */
void stl_write_sphere(FILE* f, float x, float y, float z, float radius, int segments) {
    if (segments < 3) segments = 8;
    
    float* vertices = malloc((segments + 1) * (segments + 1) * 3 * sizeof(float));
    if (!vertices) return;
    
    /* Generate vertices */
    int idx = 0;
    for (int lat = 0; lat <= segments; lat++) {
        float theta = M_PI * lat / segments;
        float sin_theta = sinf(theta);
        float cos_theta = cosf(theta);
        
        for (int lon = 0; lon <= segments; lon++) {
            float phi = 2 * M_PI * lon / segments;
            float sin_phi = sinf(phi);
            float cos_phi = cosf(phi);
            
            vertices[idx++] = x + radius * sin_theta * cos_phi;
            vertices[idx++] = y + radius * sin_theta * sin_phi;
            vertices[idx++] = z + radius * cos_theta;
        }
    }
    
    /* Generate triangles */
    for (int lat = 0; lat < segments; lat++) {
        for (int lon = 0; lon < segments; lon++) {
            int i0 = lat * (segments + 1) + lon;
            int i1 = i0 + 1;
            int i2 = i0 + segments + 1;
            int i3 = i2 + 1;
            
            float* v0 = &vertices[i0 * 3];
            float* v1 = &vertices[i1 * 3];
            float* v2 = &vertices[i2 * 3];
            float* v3 = &vertices[i3 * 3];
            
            if (lat == 0) {
                /* Top cap - single triangle */
                stl_write_triangle(f, v0, v2, v1);
            } else if (lat == segments - 1) {
                /* Bottom cap - single triangle */
                stl_write_triangle(f, v1, v2, v3);
            } else {
                /* Two triangles for quad */
                stl_write_triangle(f, v0, v2, v1);
                stl_write_triangle(f, v1, v2, v3);
            }
        }
    }
    
    free(vertices);
}

/* Write a quad as two triangles (for heightmaps) */
void stl_write_quad(FILE* f, float v00[3], float v10[3], float v11[3], float v01[3]) {
    stl_write_triangle(f, v00, v10, v11);
    stl_write_triangle(f, v00, v11, v01);
}

/* Complete STL file writing workflow */
typedef struct {
    FILE* f;
    long count_pos;
    uint32_t triangle_count;
} stl_context_t;

stl_context_t stl_begin(const char* filename, const char* description) {
    stl_context_t ctx = {0};
    ctx.f = fopen(filename, "wb");
    if (!ctx.f) return ctx;
    
    stl_write_header(ctx.f, description);
    ctx.count_pos = stl_write_count_placeholder(ctx.f);
    ctx.triangle_count = 0;
    return ctx;
}

void stl_add_triangle(stl_context_t* ctx, float v1[3], float v2[3], float v3[3]) {
    if (!ctx->f) return;
    stl_write_triangle(ctx->f, v1, v2, v3);
    ctx->triangle_count++;
}

void stl_end(stl_context_t* ctx) {
    if (!ctx->f) return;
    stl_update_count(ctx->f, ctx->count_pos, ctx->triangle_count);
    fclose(ctx->f);
    ctx->f = NULL;
}

/* Write heightmap as STL (grid of quads + side walls + bottom) */
void stl_write_heightmap(const char* filename, float** heights, int width, int height,
                          float x_scale, float y_scale, float z_scale,
                          float base_height, const char* description) {
    stl_context_t ctx = stl_begin(filename, description);
    if (!ctx.f) return;
    
    int w = width;
    int h = height;
    
    /* Top surface: each cell is a quad (2 triangles) */
    for (int y = 0; y < h - 1; y++) {
        for (int x = 0; x < w - 1; x++) {
            float v00[3] = {x * x_scale, y * y_scale, heights[y][x] * z_scale};
            float v10[3] = {(x + 1) * x_scale, y * y_scale, heights[y][x + 1] * z_scale};
            float v11[3] = {(x + 1) * x_scale, (y + 1) * y_scale, heights[y + 1][x + 1] * z_scale};
            float v01[3] = {x * x_scale, (y + 1) * y_scale, heights[y + 1][x] * z_scale};
            stl_add_triangle(&ctx, v00, v10, v11);
            stl_add_triangle(&ctx, v00, v11, v01);
        }
    }
    
    float max_x = (w - 1) * x_scale;
    float max_y = (h - 1) * y_scale;
    float base_z = base_height * z_scale;
    
    /* Side walls - Y = 0 (front) */
    for (int x = 0; x < w - 1; x++) {
        float v0[3] = {x * x_scale, 0, heights[0][x] * z_scale};
        float v1[3] = {(x + 1) * x_scale, 0, heights[0][x + 1] * z_scale};
        float v2[3] = {(x + 1) * x_scale, 0, base_z};
        float v3[3] = {x * x_scale, 0, base_z};
        stl_add_triangle(&ctx, v0, v1, v2);
        stl_add_triangle(&ctx, v0, v2, v3);
    }
    
    /* Side walls - Y = max (back) */
    for (int x = 0; x < w - 1; x++) {
        float v0[3] = {x * x_scale, max_y, heights[h - 1][x] * z_scale};
        float v1[3] = {x * x_scale, max_y, base_z};
        float v2[3] = {(x + 1) * x_scale, max_y, base_z};
        float v3[3] = {(x + 1) * x_scale, max_y, heights[h - 1][x + 1] * z_scale};
        stl_add_triangle(&ctx, v0, v1, v2);
        stl_add_triangle(&ctx, v0, v2, v3);
    }
    
    /* Side walls - X = 0 (left) */
    for (int y = 0; y < h - 1; y++) {
        float v0[3] = {0, y * y_scale, heights[y][0] * z_scale};
        float v1[3] = {0, (y + 1) * y_scale, heights[y + 1][0] * z_scale};
        float v2[3] = {0, (y + 1) * y_scale, base_z};
        float v3[3] = {0, y * y_scale, base_z};
        stl_add_triangle(&ctx, v0, v1, v2);
        stl_add_triangle(&ctx, v0, v2, v3);
    }
    
    /* Side walls - X = max (right) */
    for (int y = 0; y < h - 1; y++) {
        float v0[3] = {max_x, y * y_scale, heights[y][w - 1] * z_scale};
        float v1[3] = {max_x, y * y_scale, base_z};
        float v2[3] = {max_x, (y + 1) * y_scale, base_z};
        float v3[3] = {max_x, (y + 1) * y_scale, heights[y + 1][w - 1] * z_scale};
        stl_add_triangle(&ctx, v0, v1, v2);
        stl_add_triangle(&ctx, v0, v2, v3);
    }
    
    /* Bottom face */
    float b0[3] = {0, 0, base_z};
    float b1[3] = {max_x, 0, base_z};
    float b2[3] = {max_x, max_y, base_z};
    float b3[3] = {0, max_y, base_z};
    stl_add_triangle(&ctx, b0, b1, b2);
    stl_add_triangle(&ctx, b0, b2, b3);
    
    stl_end(&ctx);
}